# Generated by Django 5.2.7 on 2025-11-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProductos',
            fields=[
                ('pkid_cp', models.AutoField(primary_key=True, serialize=False)),
                ('desc_cp', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'categoria_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesPedido',
            fields=[
                ('pkid_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_detalle', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalles_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pkid_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(blank=True, max_length=10, null=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pedido', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('pkid_promo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_promo', models.CharField(max_length=100)),
                ('descripcion_promo', models.TextField(blank=True, null=True)),
                ('porcentaje_descuento', models.JSONField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_promo', models.CharField(blank=True, max_length=10, null=True)),
                ('imagen_promo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'promociones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('pkid_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField()),
                ('estado_reporte', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'reportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResenasNegocios',
            fields=[
                ('pkid_resena', models.AutoField(primary_key=True, serialize=False)),
                ('estrellas', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_resena', models.DateTimeField()),
                ('estado_resena', models.CharField(blank=True, max_length=9, null=True)),
                ('respuesta_vendedor', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resenas_negocios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResenasServicios',
            fields=[
                ('pkid_resena', models.AutoField(primary_key=True, serialize=False)),
                ('estrellas', models.JSONField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_resena', models.DateTimeField()),
                ('estado_resena', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'resenas_servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('pkid_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_servicio', models.CharField(blank=True, max_length=13, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('pkid_doc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=2)),
                ('desc_doc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoNegocio',
            fields=[
                ('pkid_tiponeg', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tiponeg', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_negocio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('pkid_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('pkid_rol', models.AutoField(primary_key=True, serialize=False)),
                ('desc_rol', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Negocios',
            fields=[
                ('pkid_neg', models.AutoField(primary_key=True, serialize=False)),
                ('nit_neg', models.CharField(max_length=11, unique=True)),
                ('nom_neg', models.CharField(max_length=100)),
                ('direcc_neg', models.CharField(max_length=100)),
                ('desc_neg', models.TextField(blank=True, null=True)),
                ('estado_neg', models.CharField(blank=True, max_length=10, null=True)),
                ('fechacreacion_neg', models.DateTimeField()),
                ('img_neg', models.ImageField(blank=True, null=True, upload_to='negocios/')),
                ('fktiponeg_neg', models.ForeignKey(db_column='fktiponeg_neg', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.tiponegocio')),
            ],
            options={
                'db_table': 'negocios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetodoEntrega',
            fields=[
                ('pkid_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(max_length=50)),
                ('precio_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('fknegocio', models.ForeignKey(db_column='fknegocio', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.negocios')),
            ],
            options={
                'db_table': 'metodo_entrega',
            },
        ),
        migrations.CreateModel(
            name='PagosNegocios',
            fields=[
                ('pkid_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.CharField(default='pendiente', max_length=15)),
                ('fknegocio', models.ForeignKey(db_column='fknegocio', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.negocios')),
                ('fkpedido', models.ForeignKey(db_column='fkpedido', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.pedidos')),
            ],
            options={
                'db_table': 'pagos_negocios',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('pkid_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=50)),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc_prod', models.TextField(blank=True, null=True)),
                ('estado_prod', models.CharField(blank=True, max_length=13, null=True)),
                ('stock_prod', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('img_prod', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('fecha_creacion', models.DateTimeField()),
                ('fkcategoria_prod', models.ForeignKey(db_column='fkcategoria_prod', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.categoriaproductos')),
                ('fknegocioasociado_prod', models.ForeignKey(db_column='fknegocioasociado_prod', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.negocios')),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('pkid_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fkcarrito', models.ForeignKey(db_column='fkcarrito', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.carrito')),
                ('fknegocio', models.ForeignKey(db_column='fknegocio', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.negocios')),
                ('fkproducto', models.ForeignKey(db_column='fkproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.productos')),
            ],
            options={
                'db_table': 'carrito_item',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_user', models.CharField(max_length=15, unique=True)),
                ('fechanac_user', models.DateField(blank=True, null=True)),
                ('estado_user', models.CharField(blank=True, max_length=9, null=True)),
                ('img_user', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fktipodoc_user', models.ForeignKey(db_column='fktipodoc_user', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.tipodocumento')),
                ('fkuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Software.authuser')),
            ],
            options={
                'db_table': 'usuario_perfil',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='negocios',
            name='fkpropietario_neg',
            field=models.ForeignKey(db_column='fkpropietario_neg', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.usuarioperfil'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fkusuario_carrito',
            field=models.ForeignKey(db_column='fkusuario_carrito', on_delete=django.db.models.deletion.DO_NOTHING, to='Software.usuarioperfil'),
        ),
        migrations.CreateModel(
            name='UsuariosRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkperfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Software.usuarioperfil')),
                ('fkrol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Software.roles')),
            ],
            options={
                'db_table': 'usuarios_roles',
                'managed': True,
                'unique_together': {('fkperfil', 'fkrol')},
            },
        ),
    ]
