# Generated by Django 5.2.7 on 2025-10-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negocios',
            options={'managed': True},
        ),
    ]
